---
title: "Study of PK/PD Index for Linezolid specific to CSF infections"
editor_options: 
  chunk_output_type: console
---

## Settings & Dependencies

Load necessary library, dependencies and settings for the project. Just run the block code to generate the same result than the article. Otherwise, if you want to play simulations, you can change the parameters, dosing regimens...

```{r}
#| echo: false

###############################################################
##                     Load dependcies                       ##
###############################################################
library(mrgsolve)       # Simulation package
library(dplyr)          # Data manipulation
library(tidyr)          # Data manipulation
library(purrr)          # Data manipulation
library(tibble)         # Data manipulation
library(ggplot2)        # Plotting

# If doesn't exist, create a folder for result plots
if (!dir.exists("results")) {
  dir.create("results")
}

###############################################################
##                 Specify your settings                     ##
###############################################################

# Define the maximum thread number to use for simulations
thread_number = 9

# Load the model
model_file <- mread("model/Mouse_model_v2_IV_Linear_PK")

# Specific model parameters for each strains
model_list <- list(
    # S. Aureus
    SA01943 = param(model_file, B0 = 6.3, Bmax = 9.26, Kg = 1.09,
                    Emax = 1.93, EC50 = 1.1, Kon = 0.016, MIC = 2.0)
)

# Specify AMT choosen for fractioned doses
fractioned_daily_AMT <- c(2.5, 5, 10, 20, 40, 80, 160, 320, 640, 1280)

# Specify the number of simulated patients
i_data <- expand.idata(ID = 1:1)

# Plot parameters
plot_title = "PK/PD index for Linezolid in the mouse"
plot_filename = "results/PKPD_index_plot.png"

###############################################################
##                Execute the main script                    ##
###############################################################
source("RScripts/main_script_for_mouse.R")

source("RScripts/pkpd_index_plots_script.R")

pkpd_plot <- PKPD_index_plots(obs_data = data[["sim_data"]], 
                             pred_data = data[["pred_data"]], 
                             title = plot_tile,
                             file_name = plot_filename)
```

## PK & PD Analysis

```{r}
## Summarize data
summary_fractioned <- sim_results_fractioned[["fractioned_results"]][["SA6538p"]] |>
  group_by(DoseGroup, AMT, time) |>
  summarize(
    C_CENTRAL = mean(C_CENTRAL),
    Log10CFU = mean(Log10CFU)
    )

### Plasma PK for fractioned doses
summary_fractioned |>
  filter(AMT != 0) |>
  ggplot(aes(x = time, y = C_CENTRAL, color = as.factor(DoseGroup))) +
  geom_line(linewidth = 0.75) +
  facet_wrap(~AMT, ncol = 3, scales = "free_y") +
  labs(
    x = "Time (h)", 
    y = "Linezolid concentrations (mg/L)", 
    title = "Plasma PK of Linezolid in the mouse",
    color = "Dosing regimens"
  ) +
  scale_x_continuous(breaks = seq(0, 24, 4))

### PD for fractioned doses
summary_fractioned |>
  filter(AMT != 0) |>
  ggplot(aes(x = time, y = Log10CFU, color = as.factor(DoseGroup))) +
  geom_line(linewidth = 0.75) +
  facet_wrap(~AMT, ncol = 3, scales = "free_y") +
  labs(
    x = "Time (h)", 
    y = "Bacteria count (log10 CFU/ml)", 
    title = "PD of Linezolid in the mouse",
    color = "Dosing regimens"
  ) +
  scale_x_continuous(breaks = seq(0, 24, 4))
```
