---
title: "XXXX"
author: Michael BURTIN
format: html
editor: source
editor_options: 
  chunk_output_type: console
---

Bigelow - Bioavailibility analysis
```{r}
library(minpack.lm)

# Determine a Michael model for F
f_calculation_df <- tibble(f = c(0.184, 0.233, 1, 1),
                           dose = c(10, 30, 100, 335))

# fit nls model of f_calculation_df with f in y and dose in x, and a michaelis menten mode
bioavailibility_model_01 <- nlsLM(f ~ Vmax * dose / (Km + dose), data = f_calculation_df, start = list(Vmax = 1, Km = 1))

## Result: Vmax = 1.290687 & Km = 63.448978

# another fit nls with Vmax between [0;1]
bioavailibility_model_02 <- nlsLM(f ~ Vmax * dose / (Km + dose), 
                                data = f_calculation_df, 
                                start = list(Vmax = 0.5, Km = 1), 
                                lower = c(Vmax = 0, Km = 0), 
                                upper = c(Vmax = 1, Km = Inf))

# Result: Vmax = 1.0 & Km = 36.12112
```

# Bigelow PK
```{r}
library(mrgsolve)
library(ggplot2)

# Load the model
mouse_model <- mread("model/Mouse_Bigelow")

# Define doses
ev01 <- ev(ID = 335, amt = 335, cmt = "A")
ev02 <- ev(ID = 100, amt = 100, cmt = "A")
ev03 <- ev(ID = 30, amt = 30, cmt = "A")
ev04 <- ev(ID = 10, amt = 10, cmt = "A")

dose_list <- rbind(ev01@data, ev02@data, ev03@data, ev04@data)

# Start simulations
mouse_sim_01 <- mouse_model |>
    mrgsolve::data_set(dose_list) |>
    mrgsolve::mrgsim(delta = 0.1, end = 24) |>
    tibble::as_tibble()

# Load the data
bigelow_data <- read.csv("data/bigelow_data_AIO.csv")

# Generate PK plots
ggplot() +
    geom_line(data = mouse_sim_01, aes(x = time, y = C_CENTRAL, color = factor(ID))) +
    geom_line(data = bigelow_data, aes(x = time, y = conc, color = factor(ID)), linetype = "dashed") +
    labs(title = "Bigelow PK study - Oral Bicomp PK model - Plasma concentrations",
         x = "Time (h)",
         y = "Concentration (mg/L)",
         color = "Doses") +
    scale_color_manual(values = c("335" = "purple", "100" = "cyan", "30" = "green4", "10" = "orange"), 
                       labels = c("335" = "335 mg/kg", "100" = "100 mg/kg", "30" = "30 mg/kg", "10" = "10 mg/kg")) +
    scale_y_continuous(breaks = c(0.0001, 0.001, 0.01, 0.1, 1, 10, 100, 1000), limits = c(0.0001, 1000), trans = "log10", 
                       labels = c("0.0001", "0.001", "0.01", "0.1", "1", "10",  "100", "1000")) +
    scale_x_continuous(breaks = seq(0, 24, 4)) +
    theme_minimal()

```

# Andes PK
```{r}
library(mrgsolve)
library(ggplot2)

# Load the data
andes_data <- read.csv("data/andes_data_AIO.csv")

# If we want to check another model, just change the model name in mread
mouse_model <- mread("model/Mouse_model_v2_IV_NonLinear_PK")

# Define doses
ev05 <- ev(ID = 80, amt = 80, tinf = 0.5, cmt ="CENTRAL")
ev07 <- ev(ID = 20, amt = 20, tinf = 0.5, cmt = "CENTRAL")
subcut_dose <- rbind(ev05@data, ev07@data)

# Start simulations
mouse_sim_02 <- mouse_model |>
    mrgsolve::data_set(subcut_dose) |>
    mrgsolve::mrgsim(delta = 0.1, end = 24) |>
    tibble::as_tibble()

# Generate PK plots
ggplot() +
    geom_line(data = mouse_sim_02, aes(x = time, y = C_CENTRAL, color = factor(ID))) +
    geom_line(data = andes_data, aes(x = time, y = conc, color = factor(ID)), linetype = "dashed") +
    geom_point(data = andes_data, aes(x = time, y = conc, color = factor(ID)), shape = 12) +
    scale_y_continuous(limits = c(0, 80), breaks = seq(0, 80, 10)) +
    scale_x_continuous(limits = c(0, 3)) +
    labs(title = "Andes PK study - Non-linear PK model - Plasma concentrations",
         x = "Time (h)",
         y = "Concentration (mg/L)",
         color = "Doses") +
    theme_minimal()

```

# Sandberg PK
```{r}
library(mrgsolve)
library(ggplot2)

# Load the data
sandberg_data <- read.csv("data/sandberg_data_AIO.csv")

# If we want to check another model, just change the model name in mread
mouse_model <- mread("model/Mouse_model_v2_IV_NonLinear_PK")

# Define doses
ev05 <- ev(ID = 80, amt = 80, cmt ="CENTRAL")
ev06 <- ev(ID = 40, amt = 40, cmt ="CENTRAL")
ev07 <- ev(ID = 20, amt = 20, cmt = "CENTRAL")
subcut_dose <- rbind(ev05@data, ev06@data, ev07@data)

# Start simulations
mouse_sim_02 <- mouse_model |>
    mrgsolve::data_set(subcut_dose) |>
    mrgsolve::mrgsim(delta = 0.1, end = 24) |>
    tibble::as_tibble()

# Generate PK plots
ggplot() +
    geom_line(data = mouse_sim_02, aes(x = time, y = C_CENTRAL, color = factor(ID))) +
    geom_line(data = sandberg_data, aes(x = time, y = conc, color = factor(ID)), linetype = "dashed") +
    geom_point(data = sandberg_data, aes(x = time, y = conc, color = factor(ID)), shape = 12) +
    scale_y_continuous(limits = c(0, 80), breaks = seq(0, 80, 10)) +
    scale_x_continuous(limits = c(0, 3)) +
    labs(title = "Sandberg PK study - Non-linear PK model  - Plasma concentrations",
         x = "Time (h)",
         y = "Concentration (mg/L)",
         color = "Doses") +
    theme_minimal()

```